### ISSUE TITLE
Strobe Leds on Overheat/Quick Vent

### ISSUE THREAD

**Issue by Toy203** [gpstar81/GPStar-proton-pack#295]
I see the nfilter led strobes correctly on Overheat and Quick vent but the Booster tube led is just turned on steady. Would be cool to be able to strobe both i think? Just for "lore consistency" i guess as it should be something inside the pack that open and close really fast to cool it down or whatever.

Would be also cool to have control over the color for N Filter, i personally love the red strobe effect on ribbon cable detach and would use it in my pack for quick vent too. Could follow the videogame modes as well i guess to vent "green fume" on Slime etc.

**Comment by nomakewan** [comment]
While I mostly agree with what's suggested here, there is no actual "vent" happening with slime mode intentionally, as slime operated completely differently from every single other mode in the game. Whenever you "overheat" (run out of slime) or "quick vent" when slime mode is enabled, nothing gets emitted from the pack. In full overheat there's no animation at all (other than the slime tank refilling atop the booster tube), while in quick vent there is animation but no smoke.

This is why slime behaves the way it does in V5.0.0; it's to match how it worked in the game.
