### ISSUE TITLE
Wifi  is now password protected on 5.2.1

### ISSUE THREAD

**Issue by Toy203** [gpstar81/GPStar-proton-pack#322]
Just updated all the firmware, the ESP32 is now generating a password protected wifi, it wasn't  pw protected before. Default pw (555-2368) doesn't work, or i'm having some kind of error. 
![image](https://github.com/gpstar81/GPStar-proton-pack/assets/153134073/81f77e1f-125d-45ed-acea-feb03ec800cc)

**Comment by MrPeens** [comment]
This also happened to me after upgrading to 5.1
Even after changing the password 🤷‍♂️

**Comment by Toy203** [comment]
> This also happened to me after upgrading to 5.1 Even after changing the password it won't connect. 🤷‍♂️

So yours was open before 5.1 and was password locked after you upgraded the attenuator firmware too?

**Comment by MrPeens** [comment]
> So yours was open before 5.1 and was password locked after you upgraded the attenuator firmware too?

I had my own password setup. Worked fine before the new firmware.  
Now it keeps saying I have the wrong password. Even if I reset the password and try to connect it still gives me an incorrect password error.

**Comment by nomakewan** [comment]
As a note, it should not have ever been open. The defaults for the ESP32 was always to have it be password-protected, with the Ghostbusters phone number as the password.

@DustinGrau I know you oh-so-love figuring out issues with AP mode on the ESP32...

**Comment by Toy203** [comment]
Unfortunately at this point I'm locked out from the ESP. My PCs (win11 and 10) can't connect to its wifi, and I cannot access it through android hotspot mode, although I see it connects to my phone hotspot. Unfortunately, the isolation mode thing is still in place.

**Comment by DustinGrau** [comment]
As noted, a password has always been in effect for the Wi-Fi. If you are not able to access it using either the default or your preferred password then you need to follow the instructions for uploading the "reset" firmware via the USB cable. You can find those instructions online in the guide for flashing the device. Once you have loaded that firmware it should use the default password no matter what. That should allow you access back into the device via Wi-Fi and allow you to make sure your preferred password is set. While you're connected to the Wi-Fi network for the device (using the default password) you can re-upload the standard firmware using the OTA process, and it should begin to honor your preferred password after reboot.

**Comment by DustinGrau** [comment]
I've just pushed a change into the main branch which will become a 5.2.2 release soon. This only affects the attenuator firmware: when you load the latest binary that's available, this adds a special new hardware option. When you press down and hold the center dial during bootup, it will cause the device to bypass any set password meaning the local Wi-Fi will start without any security. If you are using an ESP32 as a wireless device, you just need to add a momentary switch between pin D4 and ground and then you can press and hold that button during boot up for the same effect.

**Comment by Toy203** [comment]
Somewhat resolved by the new button reset feature I guess. Will test it as soon as I open the pack.
