### ISSUE TITLE
Disable inner cyclotron switch panel LEDs while brass pack mode is running

### ISSUE THREAD

**Issue by ProtonCharging** [gpstar81/GPStar-proton-pack#358]
### What would you like to add in terms of software changes?

The Option of Disabling the Internal Panel Lights without disconnecting any JST connectors. Could take up a spot in the LED menu if there's room, or be a third selection for the panel option on EEPROM LED menu level 2?

### Would this request involve any specific hardware?

Inner Cyclotron LED Kit (Old and Updated)

### Homework Completed

- [X] I did my part!

**Comment by Toy203** [comment]
Out of curiosity, why disable it?

**Comment by nomakewan** [comment]
Have to agree here. What is the use case?

Implementing it would be trivial for v6 (see #345 ) but I'm curious as to why.

**Comment by ProtonCharging** [comment]
I'm using the fairy lights on my proton pack to try and replicate the sparking pack's look. Ends up getting drowned out by the panel lights on the top left, and I don't wanna remove them since it'd end up just being a waste of money for me.

**Comment by nomakewan** [comment]
See now that actually makes sense. I'll go ahead and get this into 5.3.3 as a bugfix, and for v6 it can be turned into an option.

**Comment by nomakewan** [comment]
Fix has been implemented and will be a part of 5.3.3 as planned.

**Comment by ProtonCharging** [comment]
Just updated to 5.3.3, are the left two lenses by the switches supposed to still be lit? If so, is it possible to have those two go dark during the brass pack mode too? I wanna get as much spark light as I can. Thanks :)

**Comment by nomakewan** [comment]
Those two are the mode indicators for year and vibration.

Yes, I can have them turn off as well.

**Comment by ProtonCharging** [comment]
That'd be great, thank you!
