### ISSUE TITLE
[Feature]: Barrel retracting sound 

### ISSUE THREAD

**Issue by Toy203** [gpstar81/GPStar-proton-pack#373]
### What would you like to add in terms of software changes?

Could the barrel do a mechanical sound once it gets pulled back in the wand? Feels weird having a extended sound but not retracted. Also, but might be, just me, I'm in love with that sexy coil whine in the wand connected sound bit. Could be a mechanical sound with a reversed version of that whine since you are ideally putting the safe in? 

### Would this request involve any specific hardware?

Nope

### Homework Completed

- [X] I did my part!

**Comment by nomakewan** [comment]
Barrel retraction sound is added to the 5.3.4 dev branch and will be included in the next release.

**Comment by The-Y33TER** [comment]
>I'm in love with that sexy coil whine in the wand connected sound bit.

I agree, it would be great if there was a way to access the source files for certain SFX, unless there's a royalties issue, but I doubt that. Sound file "396_wand_sync.wav" ESPECIALLY.

**Comment by nomakewan** [comment]
Could you clarify what you mean by "access the source files"? I am confused.

**Comment by The-Y33TER** [comment]
> Could you clarify what you mean by "access the source files"? I am confused.

the sfx used to create the finished sounds, the source audio files and stuff, if there are any.

**Comment by nomakewan** [comment]
Almost all of the sound effects are already the "source files" by that definition; only a very small handful have modifications done by us. `396_wand_sync.wav` is, however, one of the modified files; it is made up of three sounds ripped from Ghostbusters: Spirits Unleashed. The files in question are attached to this post.

[Wand_Sync_Source_Files.zip](https://github.com/user-attachments/files/18433631/Wand_Sync_Source_Files.zip)

**Comment by The-Y33TER** [comment]
Thank you!!!
